"""
Broad disease / pathogen names for UI search (surveillance & planning).

This is **not** a full ICD-10/11 listing (tens of thousands of codes) but a large
practical set: WHO priorities, notifiable and emerging conditions, major NTDs,
zoonoses, and vaccine‑preventable diseases. Unknown names can still be typed in
the app — they are not required to appear here.
"""
from __future__ import annotations

_RAW_NAMES: tuple[str, ...] = (
    # Diarrheal & enteric
    "Cholera",
    "Typhoid fever",
    "Paratyphoid fever",
    "Shigellosis",
    "Campylobacteriosis",
    "Salmonellosis",
    "Escherichia coli infection",
    "Hemolytic uremic syndrome",
    "Norovirus infection",
    "Rotavirus gastroenteritis",
    "Cryptosporidiosis",
    "Giardiasis",
    "Amebiasis",
    "Hepatitis A",
    "Hepatitis E",
    "Clostridioides difficile infection",
    # Respiratory
    "COVID-19",
    "Influenza",
    "Seasonal influenza",
    "Influenza A",
    "Influenza B",
    "Avian influenza",
    "H5N1",
    "H5N6",
    "H7N9",
    "H9N2",
    "MERS",
    "MERS-CoV",
    "SARS",
    "SARS-CoV-1",
    "SARS-CoV-2",
    "Respiratory syncytial virus infection",
    "RSV",
    "Human metapneumovirus infection",
    "Rhinovirus infection",
    "Adenovirus infection",
    "Pertussis",
    "Diphtheria",
    "Tuberculosis",
    "Multidrug-resistant tuberculosis",
    "Extensively drug-resistant tuberculosis",
    "Legionnaires disease",
    "Legionellosis",
    "Psittacosis",
    "Q fever",
    "Pneumococcal disease",
    "Meningococcal disease",
    "Haemophilus influenzae type b infection",
    "Scarlet fever",
    "Streptococcal pharyngitis",
    # Vector-borne viral
    "Dengue fever",
    "Dengue hemorrhagic fever",
    "Chikungunya",
    "Zika virus disease",
    "Yellow fever",
    "Mayaro virus disease",
    "Oropouche fever",
    "Rift Valley fever",
    "West Nile virus infection",
    "Japanese encephalitis",
    "Saint Louis encephalitis",
    "Murray Valley encephalitis",
    "Western equine encephalitis",
    "Eastern equine encephalitis",
    "Tick-borne encephalitis",
    "Crimean-Congo hemorrhagic fever",
    "Omsk hemorrhagic fever",
    "Kyasanur Forest disease",
    "Alkhurma hemorrhagic fever",
    "Powassan virus disease",
    "La Crosse virus encephalitis",
    "Colorado tick fever",
    # VHF & high-consequence pathogens
    "Ebola virus disease",
    "Ebola",
    "Marburg virus disease",
    "Marburg",
    "Lassa fever",
    "Lujo virus disease",
    "Machupo hemorrhagic fever",
    "Bolivian hemorrhagic fever",
    "Argentine hemorrhagic fever",
    "Junin virus disease",
    "Guanarito virus disease",
    "Sabia virus disease",
    "Chapare hemorrhagic fever",
    "Hantavirus pulmonary syndrome",
    "Hemorrhagic fever with renal syndrome",
    "Mpox",
    "Monkeypox",
    "Smallpox",
    "Variola",
    # Polio & enteroviruses
    "Polio",
    "Poliomyelitis",
    "Acute flaccid myelitis",
    "Enterovirus D68 infection",
    "Enterovirus A71 infection",
    "Coxsackievirus infection",
    "Echovirus infection",
    "Hand foot and mouth disease",
    "Herpangina",
    # Measles / exanthems
    "Measles",
    "Rubella",
    "Congenital rubella syndrome",
    "Mumps",
    "Roseola",
    "Erythema infectiosum",
    "Chickenpox",
    "Varicella",
    "Herpes zoster",
    # Viral hepatitis
    "Hepatitis B",
    "Hepatitis C",
    "Hepatitis D",
    "Hepatitis B chronic",
    "Hepatitis C chronic",
    # HIV & sexual / blood-borne
    "HIV/AIDS",
    "HIV infection",
    "AIDS",
    "Acute HIV infection",
    "Syphilis",
    "Congenital syphilis",
    "Gonorrhea",
    "Chlamydia infection",
    "Chlamydia trachomatis infection",
    "Lymphogranuloma venereum",
    "Trichomoniasis",
    "Herpes simplex infection",
    # Central nervous system & prion
    "Rabies",
    "Human rabies",
    "Poliovirus infection",
    "Human T-lymphotropic virus infection",
    "Progressive multifocal leukoencephalopathy",
    "Variant Creutzfeldt-Jakob disease",
    "Creutzfeldt-Jakob disease",
    "Prion disease",
    "Subacute sclerosing panencephalitis",
    # Bacterial systemic & zoonotic
    "Anthrax",
    "Cutaneous anthrax",
    "Gastrointestinal anthrax",
    "Inhalational anthrax",
    "Brucellosis",
    "Tularemia",
    "Plague",
    "Bubonic plague",
    "Pneumonic plague",
    "Septicemic plague",
    "Meliodosis",
    "Glanders",
    "Leptospirosis",
    "Rat-bite fever",
    "Pasteurellosis",
    "Capnocytophaga infection",
    "Bartonellosis",
    "Cat-scratch disease",
    "Trench fever",
    "Ehrlichiosis",
    "Anaplasmosis",
    "Rocky Mountain spotted fever",
    "African tick-bite fever",
    "Mediterranean spotted fever",
    "Scrub typhus",
    "Epidemic typhus",
    "Murine typhus",
    "Relapsing fever",
    "Louse-borne relapsing fever",
    "Tick-borne relapsing fever",
    "Lyme disease",
    "Borreliosis",
    # NTDs & parasitic
    "Malaria",
    "Plasmodium falciparum malaria",
    "Plasmodium vivax malaria",
    "Schistosomiasis",
    "Lymphatic filariasis",
    "Onchocerciasis",
    "River blindness",
    "Trachoma",
    "Soil-transmitted helminthiasis",
    "Ascariasis",
    "Trichuriasis",
    "Hookworm infection",
    "Strongyloidiasis",
    "Leishmaniasis",
    "Visceral leishmaniasis",
    "Cutaneous leishmaniasis",
    "Mucocutaneous leishmaniasis",
    "Trypanosomiasis",
    "Human African trypanosomiasis",
    "Sleeping sickness",
    "Chagas disease",
    "American trypanosomiasis",
    "Dracunculiasis",
    "Guinea worm disease",
    "Echinococcosis",
    "Hydatid disease",
    "Cysticercosis",
    "Taeniasis",
    "Trichinellosis",
    "Fascioliasis",
    "Paragonimiasis",
    "Clonorchiasis",
    "Opisthorchiasis",
    "Toxoplasmosis",
    "Congenital toxoplasmosis",
    "Cyclosporiasis",
    "Microsporidiosis",
    "Babesiosis",
    # Diarrhea / malnutrition overlap
    "Cholera-like illness",
    "Acute watery diarrhea",
    # Meningitis & invasive bacterial
    "Bacterial meningitis",
    "Meningococcal meningitis",
    "Pneumococcal meningitis",
    "Haemophilus influenzae meningitis",
    "Listeriosis",
    "Neonatal sepsis",
    "Staphylococcal infection",
    "MRSA infection",
    "Streptococcal toxic shock syndrome",
    "Gas gangrene",
    "Clostridium perfringens infection",
    "Botulism",
    "Infant botulism",
    "Tetanus",
    "Neonatal tetanus",
    "Leprosy",
    "Hansen disease",
    "Buruli ulcer",
    "Yaws",
    "Bejel",
    "Pinta",
    "Nonvenereal treponematosis",
    "Melioidosis",
    # Fungal
    "Histoplasmosis",
    "Coccidioidomycosis",
    "Blastomycosis",
    "Paracoccidioidomycosis",
    "Talaromycosis",
    "Penicilliosis",
    "Cryptococcosis",
    "Pneumocystis pneumonia",
    "Aspergillosis",
    "Invasive candidiasis",
    "Candidemia",
    "Mucormycosis",
    "Sporotrichosis",
    "Mycetoma",
    "Chromoblastomycosis",
    # Protozoal other
    "Acanthamoeba keratitis",
    "Balamuthia infection",
    "Naegleria fowleri infection",
    "Primary amoebic meningoencephalitis",
    # Skin & neglected tropical skin
    "Leishmaniasis post-kala-azar dermatosis",
    "Podoconiosis",
    "Snakebite envenoming",
    "Scorpion sting envenoming",
    # Viral exanthem & childhood
    "Rubella-like illness",
    "Viral exanthema",
    "Acute hemorrhagic conjunctivitis",
    "Enterovirus conjunctivitis",
    # Hepatic & renal syndromes
    "Leptospirosis-associated pulmonary hemorrhage",
    "Hemorrhagic fever",
    "Undifferentiated febrile illness",
    # Respiratory viral childhood
    "Parainfluenza infection",
    "Bocavirus infection",
    "Human coronavirus infection",
    "Coronavirus HKU1 infection",
    "Coronavirus NL63 infection",
    "Coronavirus OC43 infection",
    "Coronavirus 229E infection",
    # Gastrointestinal viral
    "Astrovirus gastroenteritis",
    "Sapovirus gastroenteritis",
    # STI & pregnancy
    "Congenital cytomegalovirus infection",
    "Cytomegalovirus infection",
    "Epstein-Barr virus infection",
    "Infectious mononucleosis",
    "Parvovirus B19 infection",
    "Fifth disease",
    # Reproductive & obstetric
    "Congenital Zika syndrome",
    "Vertical transmission infection",
    # Cancer-associated infections (surveillance overlap)
    "Human papillomavirus infection",
    "Cervical HPV-related disease",
    "Helicobacter pylori-associated disease",
    "Epstein-Barr-associated malignancy",
    # Occupational / environment
    "Legionella pneumonia",
    "Pontiac fever",
    "Mycobacterium avium complex infection",
    "Nontuberculous mycobacterial infection",
    "Leprosy reaction",
    # Foodborne toxidromes
    "Ciguatera fish poisoning",
    "Scombroid fish poisoning",
    "Shellfish poisoning",
    "Paralytic shellfish poisoning",
    "Botulism foodborne",
    # Travel & importation
    "Travel-related diarrhea",
    "Imported malaria",
    "Imported dengue",
    # Animal & zoonotic (One Health)
    "Herpes B virus infection",
    "Simian foamy virus infection",
    "Orf virus infection",
    "Cowpox",
    "Vaccinia",
    "Monkey B virus",
    "Nipah virus infection",
    "Hendra virus infection",
    "Japanese encephalitis (swine cycle)",
    "Leptospirosis in animals",
    "Rift Valley fever in livestock",
    "Peste des petits ruminants",
    "Rinderpest",
    "Foot-and-mouth disease",
    "African swine fever",
    "Classical swine fever",
    "Lumpy skin disease",
    "Rabies in dogs",
    "Canine distemper",
    "Feline panleukopenia",
    "Newcastle disease",
    "Highly pathogenic avian influenza",
    "Low pathogenic avian influenza",
    "Porcine reproductive and respiratory syndrome",
    "Schmallenberg virus infection",
    "Bluetongue",
    "Epizootic hemorrhagic disease",
    "Contagious bovine pleuropneumonia",
    "Contagious caprine pleuropneumonia",
    "Anthrax in livestock",
    "Brucellosis in livestock",
    "Bovine tuberculosis",
    "Bovine spongiform encephalopathy",
    "Scrapie",
    "Chronic wasting disease",
    # Plant / crop (when host = Plant in UI)
    "Cassava brown streak disease",
    "Tomato brown rugose fruit virus",
    "Maize lethal necrosis disease",
    "Wheat rust",
    "Stem rust",
    "Rice blast",
    "Banana Xanthomonas wilt",
    "Citrus greening disease",
    "Huanglongbing",
    "Coffee leaf rust",
    "Cocoa swollen shoot disease",
    "Potato late blight",
    "Tomato bacterial wilt",
    "Fire blight",
    "Xylella fastidiosa disease",
    "Fusarium head blight",
    "Aflatoxin contamination",
    # Additional notable human names
    "Typhoid",
    "Marburg virus",
    "Ebola virus",
    "Measles virus infection",
    "Listeriosis in pregnancy",
    "Neisseria meningitidis infection",
    "Pseudomonas aeruginosa infection",
    "Acinetobacter infection",
    "Carbapenem-resistant Enterobacteriaceae infection",
    "Vancomycin-resistant Enterococcus infection",
    "Mycoplasma pneumoniae infection",
    "Chlamydia pneumoniae infection",
    "Psittacosis pneumonia",
    "Serratia infection",
    "Klebsiella pneumoniae infection",
    "Shiga toxin-producing E. coli infection",
    "Vibrio cholerae infection",
    "Vibrio vulnificus infection",
    "Non-cholera vibrio infection",
    "Cyclospora infection",
    "Isosporiasis",
    "Microcephaly-associated infection",
    "Microcephaly Zika-associated",
    "Congenital infection syndrome",
    "Fever of unknown origin",
    "Sepsis",
    "Septic shock",
    "Acute respiratory distress syndrome",
    "Pneumonia",
    "Severe pneumonia",
    "CAP",
    "HAP",
    "VAP",
    "Bronchiolitis",
    "Croup",
    "Pertussis-like illness",
    "Diphtheria cutaneous",
    "Scarlet fever invasive",
    "Rheumatic fever",
    "Post-streptococcal glomerulonephritis",
    "Malaria in pregnancy",
    "Severe malaria",
    "Hyperreactive malarial splenomegaly",
    "Blackwater fever",
    "Dengue shock syndrome",
    "Severe dengue",
    "Congenital Chagas disease",
    "Oral cholera vaccine reaction",
    "Yellow fever vaccine-associated viscerotropic disease",
    "Influenza-like illness",
    "ILI",
    "SARI",
    "ARI",
    "COVID-19 long",
    "Post-acute sequelae of COVID-19",
    "Multisystem inflammatory syndrome in children",
    "MIS-C",
    "Multisystem inflammatory syndrome in adults",
    "MIS-A",
    "Kawasaki-like disease",
    "Acute rheumatic fever",
    "Stevens-Johnson syndrome infection-associated",
    "Toxic shock syndrome staphylococcal",
    "Toxic shock syndrome streptococcal",
    "Necrotizing fasciitis",
    "Burkholderia pseudomallei infection",
    "Burkholderia mallei infection",
    "Chromobacterium infection",
    "Elizabethkingia infection",
    "Cronobacter infection",
    "Infant formula-associated sepsis",
    # Mental model / syndromic
    "Febrile rash illness",
    "Neurologic infectious disease",
    "Acute flaccid paralysis surveillance",
    "Acute gastroenteritis outbreak",
    "Respiratory disease outbreak",
    "Hemorrhagic fever outbreak investigation",
    # Regional / outbreak labels sometimes used in media
    "Lassa fever Nigeria",
    "Ebola outbreak response",
    "Marburg outbreak",
    "Measles outbreak",
    "Cholera outbreak",
    "Meningitis belt epidemic",
    "Serogroup A meningococcal disease",
    "Serogroup W meningococcal disease",
    "Serogroup X meningococcal disease",
    "Neonatal tetanus elimination surveillance",
    "Guillain-Barré syndrome post-infection",
    "Zika-associated Guillain-Barré syndrome",
    # Additional pathogens (synonyms)
    "Norwalk virus",
    "Norovirus",
    "Calicivirus gastroenteritis",
    "Adeno-associated virus research",
    "Bunyavirus infection",
    "Phlebovirus infection",
    "Hantavirus infection",
    "Arenavirus infection",
    "Filovirus infection",
    "Paramyxovirus infection",
    "Henipavirus infection",
    "Reovirus infection",
    "Rotavirus A",
    "Enterovirus infection",
    "Parechovirus infection",
    "Cardiovirus infection",
    "Rubulavirus infection",
    "Orthopoxvirus infection",
    "Vaccinia virus infection",
    "Mpox virus infection",
    "Herpesvirus infection",
    "Varicella-zoster virus infection",
    "Human herpesvirus 6 infection",
    "Human herpesvirus 7 infection",
    "Human herpesvirus 8 infection",
    "Kaposi sarcoma-associated herpesvirus infection",
)


def world_surveillance_disease_names() -> tuple[str, ...]:
    """Deduplicated names, title-stable first occurrence, sorted alphabetically (case-insensitive)."""
    seen: set[str] = set()
    out: list[str] = []
    for x in _RAW_NAMES:
        s = (x or "").strip()
        if not s:
            continue
        k = s.casefold()
        if k in seen:
            continue
        seen.add(k)
        out.append(s)
    out.sort(key=str.casefold)
    return tuple(out)
